security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
        App\Entity\User:
            algorithm: auto

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewall configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            # Configure form login
            form_login:
                login_path: app_login
                check_path: app_login_check
                enable_csrf: true
                default_target_path: app_dashboard
                username_parameter: _username
                password_parameter: _password
                use_referer: true
                
            # Configure API login
            json_login:
                check_path: /api/auth/login
                
            # Configure logout
            logout:
                path: app_logout
                target: app_home
                
            # Remember me functionality
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

    # Access control
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/ping, roles: PUBLIC_ACCESS }
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/status, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: ROLE_ADMIN }
