version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony7-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - symfony7-network


  webserver:
    image: nginx:alpine
    container_name: symfony7-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - symfony7-network

networks:
  symfony7-network:
    driver: bridge
